export * from './HomePage/HomePage'
export * from './AboutPage/AboutPage'
export * from './NotFounPage/NotFoundPage'
export * from './PostPage/PostPage'
export * from './UserPage/UserPage'
export * from './SinglePostPage/SinglePostPage'
export * from './SingleUserPage/SingleUserPage'
export * from './LoginPage/LoginPage'
